In [1]:
import  pandas as pd 


In [2]:
data=pd.read_json("News_Category_Dataset_v3.json",lines=True)

In [3]:
data.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22


In [4]:
data.shape

(209527, 6)

In [5]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='str')

In [6]:
data=data['short_description'].sample(20000,random_state=42)

In [7]:
data.isnull().sum()

np.int64(0)

In [8]:
data.duplicated().sum()

np.int64(1994)

In [9]:
data.drop_duplicates(inplace=True)

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
data.head()

128310    What if, in doing so, we won't just create new...
139983    It should have been a glorious week for AOL ch...
42339     A few protesters who refused to leave remained...
131494                                                     
163649    Scientists didn't know if humans played that g...
Name: short_description, dtype: str

In [12]:
data.shape


(18006,)

In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [14]:
tokenizer=Tokenizer(oov_token="OOV")

In [15]:
tokenizer.fit_on_texts(data)

In [16]:
tokenizer.word_index

{'OOV': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'is': 8,
 'that': 9,
 'for': 10,
 'i': 11,
 'you': 12,
 'on': 13,
 'it': 14,
 'with': 15,
 'are': 16,
 'be': 17,
 'we': 18,
 'this': 19,
 'as': 20,
 'have': 21,
 'was': 22,
 'but': 23,
 'your': 24,
 'at': 25,
 'not': 26,
 'from': 27,
 'my': 28,
 'or': 29,
 'an': 30,
 'our': 31,
 'by': 32,
 'has': 33,
 'about': 34,
 'more': 35,
 'one': 36,
 'can': 37,
 'when': 38,
 'what': 39,
 'all': 40,
 'their': 41,
 'out': 42,
 'they': 43,
 'his': 44,
 "it's": 45,
 'new': 46,
 'will': 47,
 'if': 48,
 'he': 49,
 'who': 50,
 'time': 51,
 'up': 52,
 'so': 53,
 'her': 54,
 'just': 55,
 'like': 56,
 'people': 57,
 'do': 58,
 'how': 59,
 'been': 60,
 'some': 61,
 'there': 62,
 'said': 63,
 'no': 64,
 'me': 65,
 'than': 66,
 'most': 67,
 'us': 68,
 'year': 69,
 'day': 70,
 'get': 71,
 'after': 72,
 'would': 73,
 'many': 74,
 'make': 75,
 'into': 76,
 'she': 77,
 'had': 78,
 'know': 79,
 'first': 80,
 'over': 81,
 'these': 82,
 'years'

In [17]:
len(tokenizer.word_index)

29282

In [18]:
data=tokenizer.texts_to_sequences(data)

In [19]:
data

[[39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547,
  9,
  89,
  26,
  21,
  1582,
  4864],
 [14,
  138,
  21,
  60,
  4,
  4445,
  115,
  10,
  8480,
  781,
  1017,
  2785,
  7128,
  44,
  8481,
  8482,
  10762,
  795,
  809],
 [4, 164, 1966, 50, 2128, 3, 474, 2786, 25, 2, 1324, 809],
 [],
 [1286,
  319,
  79,
  48,
  1121,
  1367,
  9,
  397,
  20,
  142,
  23,
  7,
  2,
  101,
  608,
  83,
  1486,
  2940,
  184,
  1368,
  6,
  796],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105, 4865, 4, 10763, 10, 24, 229],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12,
  30,
  537,
  3,
  1487,
  24,
  1447],
 [32,
  810,
  15034,
  15035,
  3787,
  4446,
  39,
  73,
  14,
  111,
  3,
  582,
  4,
  35,
  782,
  5403,
  3109,
  39,
  2941,
  269]

In [20]:
data[0]

[39,
 48,
 7,
 318,
 53,
 18,
 485,
 55,
 582,
 46,
 1690,
 10,
 446,
 1446,
 110,
 8479,
 300,
 3,
 582,
 46,
 1690,
 10,
 31,
 547,
 9,
 89,
 26,
 21,
 1582,
 4864]

In [21]:
input_sentances=[]
for sent in data:
    if len(sent)<2:
        continue
    for i in range(1,len(sent)):
        ngram=sent[:i+1]
        input_sentances.append(ngram)

In [22]:
input_sentances

[[39, 48],
 [39, 48, 7],
 [39, 48, 7, 318],
 [39, 48, 7, 318, 53],
 [39, 48, 7, 318, 53, 18],
 [39, 48, 7, 318, 53, 18, 485],
 [39, 48, 7, 318, 53, 18, 485, 55],
 [39, 48, 7, 318, 53, 18, 485, 55, 582],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10, 446],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10, 446, 1446],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10, 446, 1446, 110],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10, 446, 1446, 110, 8479],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582],
 [39,
  48,
 

In [23]:
max_len=max([len(i) for i in input_sentances])

In [24]:
max_len

167

In [25]:
input=pad_sequences(input_sentances,padding='pre',maxlen=max_len)

In [26]:
input


array([[  0,   0,   0, ...,   0,  39,  48],
       [  0,   0,   0, ...,  39,  48,   7],
       [  0,   0,   0, ...,  48,   7, 318],
       ...,
       [  0,   0,   0, ...,   6, 609,  12],
       [  0,   0,   0, ..., 609,  12, 100],
       [  0,   0,   0, ...,  12, 100, 116]],
      shape=(375340, 167), dtype=int32)

In [27]:
input[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 39, 48,  7],
      dtype=int32)

In [28]:
input.shape

(375340, 167)

In [29]:
X=input[:,:-1]

In [30]:
X.shape


(375340, 166)

In [31]:
Y=input[:,-1]

In [32]:
Y

array([ 48,   7, 318, ...,  12, 100, 116], shape=(375340,), dtype=int32)

In [33]:
Y.shape

(375340,)

In [34]:
## Train Test split
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [36]:
X_train.shape

(300272, 166)

In [37]:
max_len=X.shape[1]
max_len

166

In [38]:
vocab_size=len(tokenizer.word_index)+1

In [39]:
vocab_size

29283

In [40]:
model=Sequential([Embedding(vocab_size,128,input_length=max_len),LSTM(256),Dense(vocab_size,activation='softmax')])

c:\Users\tripa\OneDrive\Desktop\IIITR B.TECH\GEN-AI\4.Deep_Learning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [42]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [43]:
model.build(input_shape=(None,max_len))

In [44]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 166, 128)       │     3,748,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 29283)          │     7,525,731 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,668,195 (44.51 MB)

 Trainable params: 11,668,195 (44.51 MB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10)

Epoch 1/10
4729/9384 ━━━━━━━━━━━━━━━━━━━━ 34:40 447ms/step - accuracy: 0.0722 - loss: 7.3711

KeyboardInterrupt: 

In [ ]:
model.save('Next_word_pred.h5')

In [ ]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)
    

In [52]:
data2=pd.read_json("News_Category_Dataset_v3.json",lines=True)
data2

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28


In [53]:
data2=data2['short_description']

In [54]:
data2

0         Health experts said it is too early to predict...
1         He was subdued by passengers and crew when he ...
2         "Until you have a dog you don't understand wha...
3         "Accidentally put grown-up toothpaste on my to...
4         Amy Cooper accused investment firm Franklin Te...
                                ...                        
209522    Verizon Wireless and AT&T are already promotin...
209523    Afterward, Azarenka, more effusive with the pr...
209524    Leading up to Super Bowl XLVI, the most talked...
209525    CORRECTION: An earlier version of this story i...
209526    The five-time all-star center tore into his te...
Name: short_description, Length: 209527, dtype: str

In [55]:
df=pd.DataFrame(data2)

In [56]:
df

,short_description
0,Health experts said it is too early to predict...
1,He was subdued by passengers and crew when he ...
2,"""Until you have a dog you don't understand wha..."
3,"""Accidentally put grown-up toothpaste on my to..."
4,Amy Cooper accused investment firm Franklin Te...
...,...
209522,Verizon Wireless and AT&T are already promotin...
209523,"Afterward, Azarenka, more effusive with the pr..."
209524,"Leading up to Super Bowl XLVI, the most talked..."
209525,CORRECTION: An earlier version of this story i...


In [57]:
df.to_csv('data.csv')